# Generated by Django 5.0.3 on 2024-03-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='user_skill',
            field=models.IntegerField(default=0, verbose_name='User Skill'),
        ),
    ]
